### ISSUE TITLE
Caused by: javax.persistence.PersistenceException: java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed

### ISSUE THREAD

**Issue by dyrnq** [dyrnq/docker-canal#1]
```bash
canal-admin-1     | 2024-10-18 03:48:07.688 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ebeanServer' defined in class path resource [com/alibaba/otter/canal/admin/config/EbeanConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.ebean.EbeanServer]: Factory method 'ebeanServer' threw exception; nested exception is javax.persistence.PersistenceException: java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed
canal-admin-1     | 2024-10-18 03:48:07.691 [main] INFO  org.apache.catalina.core.StandardService - Stopping service [Tomcat]
canal-admin-1     | 2024-10-18 03:48:07.703 [main] INFO  o.s.b.a.logging.ConditionEvaluationReportLoggingListener - 
canal-admin-1     | 
canal-admin-1     | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
canal-admin-1     | 2024-10-18 03:48:07.721 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
canal-admin-1     | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ebeanServer' defined in class path resource [com/alibaba/otter/canal/admin/config/EbeanConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.ebean.EbeanServer]: Factory method 'ebeanServer' threw exception; nested exception is javax.persistence.PersistenceException: java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed
canal-admin-1     |     at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
canal-admin-1     |     at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
canal-admin-1     |     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
canal-admin-1     |     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
canal-admin-1     |     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
canal-admin-1     |     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
canal-admin-1     |     at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
canal-admin-1     |     at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
canal-admin-1     |     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
canal-admin-1     |     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
canal-admin-1     |     at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
canal-admin-1     |     at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920)
canal-admin-1     |     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
canal-admin-1     |     at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
canal-admin-1     |     at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:780)
canal-admin-1     |     at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:453)
canal-admin-1     |     at org.springframework.boot.SpringApplication.run(SpringApplication.java:343)
canal-admin-1     |     at com.alibaba.otter.canal.admin.CanalAdminApplication.main(CanalAdminApplication.java:19)
canal-admin-1     | Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.ebean.EbeanServer]: Factory method 'ebeanServer' threw exception; nested exception is javax.persistence.PersistenceException: java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed
canal-admin-1     |     at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
canal-admin-1     |     at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
canal-admin-1     |     ... 17 common frames omitted
canal-admin-1     | Caused by: javax.persistence.PersistenceException: java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed
canal-admin-1     |     at io.ebeaninternal.server.core.DefaultContainer.checkDataSource(DefaultContainer.java:323)
canal-admin-1     |     at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:106)
canal-admin-1     |     at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:35)
canal-admin-1     |     at io.ebean.EbeanServerFactory.createInternal(EbeanServerFactory.java:109)
canal-admin-1     |     at io.ebean.EbeanServerFactory.create(EbeanServerFactory.java:70)
canal-admin-1     |     at com.alibaba.otter.canal.admin.config.EbeanConfig.ebeanServer(EbeanConfig.java:39)
canal-admin-1     |     at com.alibaba.otter.canal.admin.config.EbeanConfig$$EnhancerBySpringCGLIB$$a76cbc01.CGLIB$ebeanServer$0(<generated>)
canal-admin-1     |     at com.alibaba.otter.canal.admin.config.EbeanConfig$$EnhancerBySpringCGLIB$$a76cbc01$$FastClassBySpringCGLIB$$d0e3f930.invoke(<generated>)
canal-admin-1     |     at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
canal-admin-1     |     at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
canal-admin-1     |     at com.alibaba.otter.canal.admin.config.EbeanConfig$$EnhancerBySpringCGLIB$$a76cbc01.ebeanServer(<generated>)
canal-admin-1     |     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
canal-admin-1     |     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
canal-admin-1     |     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
canal-admin-1     |     at java.lang.reflect.Method.invoke(Method.java:498)
canal-admin-1     |     at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
canal-admin-1     |     ... 18 common frames omitted
canal-admin-1     | Caused by: java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed
canal-admin-1     |     at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:111)
canal-admin-1     |     at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
canal-admin-1     |     at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)
canal-admin-1     |     at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)
canal-admin-1     |     at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
canal-admin-1     |     at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
canal-admin-1     |     at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
canal-admin-1     |     at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
canal-admin-1     |     at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
canal-admin-1     |     at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
canal-admin-1     |     at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
canal-admin-1     |     at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
canal-admin-1     |     at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
canal-admin-1     |     at io.ebeaninternal.server.core.DefaultContainer.checkDataSource(DefaultContainer.java:316)
canal-admin-1     |     ... 33 common frames omitted
canal-admin-1     | Caused by: com.mysql.cj.exceptions.UnableToConnectException: Public Key Retrieval is not allowed
canal-admin-1     |     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
canal-admin-1     |     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
canal-admin-1     |     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
canal-admin-1     |     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
canal-admin-1     |     at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
canal-admin-1     |     at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:86)
canal-admin-1     |     at com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:130)
canal-admin-1     |     at com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:49)
canal-admin-1     |     at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:443)
canal-admin-1     |     at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:213)
canal-admin-1     |     at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1430)
canal-admin-1     |     at com.mysql.cj.NativeSession.connect(NativeSession.java:134)
canal-admin-1     |     at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:945)
canal-admin-1     |     at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:815)
canal-admin-1     |     ... 44 common frames omitted

```

**Comment by dyrnq** [comment]
Appended `allowPublicKeyRetrieval=true` to `spring.datasource.url`.

```bash
spring.datasource.url=jdbc:mysql://canal-admin-db:3306/canal_manager?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
```
