### ISSUE TITLE
 java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file

### ISSUE THREAD

**Issue by dyrnq** [dyrnq/docker-canal#26]
```bash
 11:59:51.353 [ZkClient-EventThread-28-zoo1:2181,zoo2:2181,zoo3:2181] INFO  c.a.o.c.p.CanalInstanceExports - Successfully register metrics for instance test.
 11:59:51.353 [ZkClient-EventThread-28-zoo1:2181,zoo2:2181,zoo3:2181] INFO  c.a.o.c.prometheus.PrometheusService - Register metrics for destination test.
 11:59:51.353 [ZkClient-EventThread-28-zoo1:2181,zoo2:2181,zoo3:2181] INFO  c.a.o.c.i.s.CanalInstanceWithSpring - start CannalInstance for 1-test 
 11:59:51.598 [ZkClient-EventThread-28-zoo1:2181,zoo2:2181,zoo3:2181] INFO  c.alibaba.druid.pool.DruidDataSource - {dataSource-1} inited
 11:59:51.799 [ZkClient-EventThread-28-zoo1:2181,zoo2:2181,zoo3:2181] INFO  c.a.o.c.p.i.m.t.DefaultTableMetaTSDBFactory - test init TableMetaTSDB with classpath:spring/tsdb/mysql-tsdb.xml
 11:59:51.802 [ZkClient-EventThread-28-zoo1:2181,zoo2:2181,zoo3:2181] WARN  c.a.o.c.p.i.m.dbsync.LogEventConvert - --> init table filter : ^.*\..*$
 11:59:51.802 [ZkClient-EventThread-28-zoo1:2181,zoo2:2181,zoo3:2181] WARN  c.a.o.c.p.i.m.dbsync.LogEventConvert - --> init table black filter : 
 11:59:51.805 [ZkClient-EventThread-28-zoo1:2181,zoo2:2181,zoo3:2181] INFO  c.a.o.c.i.core.AbstractCanalInstance - start successful....
 11:59:51.806 [ZkClient-EventThread-28-zoo1:2181,zoo2:2181,zoo3:2181] INFO  c.a.o.c.s.e.CanalServerWithEmbedded - start CanalInstances[test] successfully
 11:59:51.806 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.i.m.r.RdsBinlogEventParserProxy - start heart beat.... 
 11:59:51.806 [ZkClient-EventThread-28-zoo1:2181,zoo2:2181,zoo3:2181] INFO  c.a.o.canal.server.CanalMQStarter - ## Start the MQ work of destination:test
 11:59:51.806 [pool-2-thread-1] INFO  c.a.o.canal.server.CanalMQStarter - ## start the MQ producer: test.
 11:59:51.807 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection to main-db8/172.224.0.3:3306...
 11:59:51.811 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
main-db8-1         | 2024-10-22T03:59:51.813369Z 8 [Warning] [MY-013360] [Server] Plugin mysql_native_password reported: ''mysql_native_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
 11:59:51.811 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth plugin: caching_sha2_password
 11:59:51.813 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - client authentication packet is sent out.
 11:59:51.813 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth switch pluginName is mysql_native_password.
 11:59:51.814 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth switch response packet is sent out.
 11:59:51.807 [pool-2-thread-1] INFO  c.a.o.c.s.e.CanalServerWithEmbedded - subscribe successfully, ClientIdentity[destination=test,clientId=1001,filter=] with first position:null 
 11:59:51.816 [pool-2-thread-1] INFO  c.a.o.canal.server.CanalMQStarter - ## the MQ producer: test is running now ......
 11:59:51.822 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection in sslMode DISABLED, Ssl_version:, Ssl_cipher:
 11:59:51.863 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection to main-db8/172.224.0.3:3306...
 11:59:51.864 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
 11:59:51.864 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth plugin: caching_sha2_password
 11:59:51.864 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - client authentication packet is sent out.
 11:59:51.864 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth switch pluginName is mysql_native_password.
 11:59:51.864 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth switch response packet is sent out.
 11:59:51.867 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection in sslMode DISABLED, Ssl_version:, Ssl_cipher:
 11:59:51.871 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] WARN  c.a.o.c.p.i.m.r.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
 11:59:51.874 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] ERROR c.a.o.c.p.i.m.r.RdsBinlogEventParserProxy - dump address main-db8/172.224.0.3:3306 has an error, retrying. caused by 
 com.alibaba.otter.canal.parse.exception.CanalParseException: use gtid and TableMeta TSDB should be config timestamp > 0
 11:59:51.875 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] ERROR c.a.o.c.common.alarm.LogAlarmHandler - destination:test[com.alibaba.otter.canal.parse.exception.CanalParseException: use gtid and TableMeta TSDB should be config timestamp > 0
 ]
 11:59:51.876 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - disConnect MysqlConnection to main-db8/172.224.0.3:3306...
 11:59:51.877 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - disConnect MysqlConnection to main-db8/172.224.0.3:3306...
 12:00:02.035 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection to main-db8/172.224.0.3:3306...
 12:00:02.035 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
 12:00:02.035 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth plugin: caching_sha2_password
 12:00:02.036 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - client authentication packet is sent out.
 12:00:02.036 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth switch pluginName is mysql_native_password.
 12:00:02.036 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth switch response packet is sent out.
 12:00:02.037 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection in sslMode DISABLED, Ssl_version:, Ssl_cipher:
 12:00:02.043 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection to main-db8/172.224.0.3:3306...
 12:00:02.043 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
 12:00:02.043 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth plugin: caching_sha2_password
 12:00:02.043 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - client authentication packet is sent out.
 12:00:02.043 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth switch pluginName is mysql_native_password.
 12:00:02.043 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth switch response packet is sent out.
 12:00:02.045 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection in sslMode DISABLED, Ssl_version:, Ssl_cipher:
 12:00:02.047 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] WARN  c.a.o.c.p.i.m.r.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
 12:00:02.047 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - disConnect MysqlConnection to main-db8/172.224.0.3:3306...
 12:00:02.047 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection to main-db8/172.224.0.3:3306...
 12:00:02.047 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
 12:00:02.047 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth plugin: caching_sha2_password
 12:00:02.048 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - client authentication packet is sent out.
 12:00:02.048 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth switch pluginName is mysql_native_password.
 12:00:02.048 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth switch response packet is sent out.
 12:00:02.049 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection in sslMode DISABLED, Ssl_version:, Ssl_cipher:
 12:00:02.051 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] WARN  c.a.o.c.p.i.mysql.MysqlConnection - load MySQL @@version_comment : MySQL Community Server - GPL
 12:00:02.051 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.i.mysql.MysqlConnection - COM_BINLOG_DUMP with position:BinlogDumpCommandPacket[binlogPosition=4,slaveServerId=5555555,binlogFileName=mysql-bin.000001,command=18]
 12:00:02.059 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] ERROR c.a.o.c.p.i.m.d.DirectLogFetcher - I/O error while reading from client socket
 java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
    at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:167)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:787)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findPositionWithMasterIdAndTimestamp(MysqlEventParser.java:401)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:447)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:360)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:186)
    at java.base/java.lang.Thread.run(Thread.java:1583)
 12:00:02.059 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] ERROR c.a.o.c.p.i.m.r.RdsBinlogEventParserProxy - ERROR ## findAsPerTimestampInSpecificLogFile has an error
 java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
    at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:167)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:787)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findPositionWithMasterIdAndTimestamp(MysqlEventParser.java:401)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:447)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:360)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:186)
    at java.base/java.lang.Thread.run(Thread.java:1583)
 12:00:02.059 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] ERROR c.a.o.c.p.i.m.r.RdsBinlogEventParserProxy - dump address main-db8/172.224.0.3:3306 has an error, retrying. caused by 
 com.alibaba.otter.canal.parse.exception.CanalParseException: [fixed timestamp] can't found begin/commit position before with fixed position mysql-bin.000001:4
 12:00:02.060 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] ERROR c.a.o.c.common.alarm.LogAlarmHandler - destination:test[com.alibaba.otter.canal.parse.exception.CanalParseException: [fixed timestamp] can't found begin/commit position before with fixed position mysql-bin.000001:4
 ]
 12:00:02.060 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - disConnect MysqlConnection to main-db8/172.224.0.3:3306...
 12:00:02.060 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - disConnect MysqlConnection to main-db8/172.224.0.3:3306...
 12:00:02.060 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection to main-db8/172.224.0.3:3306...
 12:00:02.060 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
 12:00:02.060 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth plugin: caching_sha2_password
 12:00:02.060 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - client authentication packet is sent out.
 12:00:02.061 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth switch pluginName is mysql_native_password.
 12:00:02.061 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth switch response packet is sent out.
 12:00:02.062 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection in sslMode DISABLED, Ssl_version:, Ssl_cipher:
 12:00:02.063 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - KILL DUMP 12 failure
 java.io.IOException: ErrorPacket [errorNumber=1094, fieldCount=-1, message=Unknown thread id: 12, sqlState=HY000, sqlStateMarker=#]
  with command: KILL CONNECTION 12
    at com.alibaba.otter.canal.parse.driver.mysql.MysqlUpdateExecutor.update(MysqlUpdateExecutor.java:49)
    at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:137)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.disconnect(MysqlConnection.java:112)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:307)
    at java.base/java.lang.Thread.run(Thread.java:1583)
 12:00:02.063 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - disConnect MysqlConnection to main-db8/172.224.0.3:3306...
 12:00:16.576 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection to main-db8/172.224.0.3:3306...
 12:00:16.577 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
 12:00:16.577 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth plugin: caching_sha2_password
 12:00:16.577 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - client authentication packet is sent out.
 12:00:16.577 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth switch pluginName is mysql_native_password.
 12:00:16.577 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth switch response packet is sent out.
 12:00:16.578 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection in sslMode DISABLED, Ssl_version:, Ssl_cipher:
 12:00:16.583 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection to main-db8/172.224.0.3:3306...
 12:00:16.583 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
 12:00:16.583 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth plugin: caching_sha2_password
 12:00:16.583 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - client authentication packet is sent out.
 12:00:16.583 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth switch pluginName is mysql_native_password.
 12:00:16.583 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth switch response packet is sent out.
 12:00:16.585 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection in sslMode DISABLED, Ssl_version:, Ssl_cipher:
 12:00:16.586 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] WARN  c.a.o.c.p.i.m.r.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
 12:00:16.586 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - disConnect MysqlConnection to main-db8/172.224.0.3:3306...
 12:00:16.586 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection to main-db8/172.224.0.3:3306...
 12:00:16.587 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
 12:00:16.587 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth plugin: caching_sha2_password
 12:00:16.587 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - client authentication packet is sent out.
 12:00:16.587 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth switch pluginName is mysql_native_password.
 12:00:16.587 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth switch response packet is sent out.
 12:00:16.589 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection in sslMode DISABLED, Ssl_version:, Ssl_cipher:
 12:00:16.590 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] WARN  c.a.o.c.p.i.mysql.MysqlConnection - load MySQL @@version_comment : MySQL Community Server - GPL
 12:00:16.590 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.i.mysql.MysqlConnection - COM_BINLOG_DUMP with position:BinlogDumpCommandPacket[binlogPosition=4,slaveServerId=5555555,binlogFileName=mysql-bin.000001,command=18]
 12:00:16.590 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] ERROR c.a.o.c.p.i.m.d.DirectLogFetcher - I/O error while reading from client socket
 java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
    at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:167)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:787)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findPositionWithMasterIdAndTimestamp(MysqlEventParser.java:401)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:447)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:360)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:186)
    at java.base/java.lang.Thread.run(Thread.java:1583)
 12:00:16.590 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] ERROR c.a.o.c.p.i.m.r.RdsBinlogEventParserProxy - ERROR ## findAsPerTimestampInSpecificLogFile has an error
 java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
    at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:167)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:787)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findPositionWithMasterIdAndTimestamp(MysqlEventParser.java:401)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:447)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:360)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:186)
    at java.base/java.lang.Thread.run(Thread.java:1583)
 12:00:16.591 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] ERROR c.a.o.c.p.i.m.r.RdsBinlogEventParserProxy - dump address main-db8/172.224.0.3:3306 has an error, retrying. caused by 
 com.alibaba.otter.canal.parse.exception.CanalParseException: [fixed timestamp] can't found begin/commit position before with fixed position mysql-bin.000001:4
 12:00:16.591 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] ERROR c.a.o.c.common.alarm.LogAlarmHandler - destination:test[com.alibaba.otter.canal.parse.exception.CanalParseException: [fixed timestamp] can't found begin/commit position before with fixed position mysql-bin.000001:4
 ]
 12:00:16.591 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - disConnect MysqlConnection to main-db8/172.224.0.3:3306...
 12:00:16.591 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - disConnect MysqlConnection to main-db8/172.224.0.3:3306...
 12:00:16.591 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection to main-db8/172.224.0.3:3306...
 12:00:16.591 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
 12:00:16.591 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth plugin: caching_sha2_password
 12:00:16.592 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - client authentication packet is sent out.
 12:00:16.592 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth switch pluginName is mysql_native_password.
 12:00:16.592 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth switch response packet is sent out.
 12:00:16.593 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection in sslMode DISABLED, Ssl_version:, Ssl_cipher:
 12:00:16.594 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - KILL DUMP 16 failure
 java.io.IOException: ErrorPacket [errorNumber=1094, fieldCount=-1, message=Unknown thread id: 16, sqlState=HY000, sqlStateMarker=#]
  with command: KILL CONNECTION 16
    at com.alibaba.otter.canal.parse.driver.mysql.MysqlUpdateExecutor.update(MysqlUpdateExecutor.java:49)
    at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:137)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.disconnect(MysqlConnection.java:112)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:307)
    at java.base/java.lang.Thread.run(Thread.java:1583)
 12:00:16.594 [destination = test , address = main-db8/172.224.0.3:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - disConnect MysqlConnection to main-db8/172.224.0.3:3306...
```

**Comment by dyrnq** [comment]
- mysql5
```bash
+------------------+-----------+
| Log_name         | File_size |
+------------------+-----------+
| mysql-bin.000001 |       177 |
| mysql-bin.000002 |   2949916 |
| mysql-bin.000003 |       154 |
+------------------+-----------+
```
- mysql8

```bash
+---------------+-----------+-----------+
| Log_name      | File_size | Encrypted |
+---------------+-----------+-----------+
| binlog.000001 |   3296532 | No        |
| binlog.000002 |       157 | No        |
+---------------+-----------+-----------+
```

**Comment by dyrnq** [comment]
修改
`canal.instance.master.journal.name=mysql-bin.000001`
为
`canal.instance.master.journal.name=binlog.000001`
