### ISSUE TITLE
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because "pkNames" is null

### ISSUE THREAD

**Issue by dyrnq** [dyrnq/docker-canal#28]
```bash
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because "pkNames" is null
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:157)
	at com.alibaba.otter.canal.client.adapter.ProxyOuterAdapter.sync(ProxyOuterAdapter.java:42)
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.batchSync(AdapterProcessor.java:142)
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$writeOut$1(AdapterProcessor.java:100)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$writeOut$2(AdapterProcessor.java:97)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because "pkNames" is null
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbMirrorDbSyncService.initMappingConfig(RdbMirrorDbSyncService.java:140)
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbMirrorDbSyncService.sync(RdbMirrorDbSyncService.java:82)
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:155)
	... 9 common frames omitted
2024-10-23 11:09:38.233 [Thread-3] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - Outer adapter sync failed!  Error sync and rollback, execute times: 1
2024-10-23 11:09:39.235 [pool-8-thread-1] DEBUG c.a.o.c.c.adapter.rdb.service.RdbMirrorDbSyncService - DDL: {"data":null,"database":"mytest2","destination":"mytest2","es":1729652961000,"groupId":"g1-mysql","isDdl":true,"old":null,"pkNames":null,"sql":"DROP TABLE IF EXISTS `person` /* generated by server */","table":"person","ts":1729652962076,"type":"ERASE"}
2024-10-23 11:09:39.255 [pool-8-thread-1] DEBUG c.a.o.c.c.adapter.rdb.service.RdbMirrorDbSyncService - DDL: {"data":null,"database":"mytest2","destination":"mytest2","es":1729652961000,"groupId":"g1-mysql","isDdl":true,"old":null,"pkNames":null,"sql":"CREATE TABLE `person` (\r\n  `id` int DEFAULT NULL,\r\n  `last_name` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,\r\n  `first_name` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,\r\n  `address` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,\r\n  `city` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,\r\n  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin","table":"person","ts":1729652962076,"type":"CREATE"}
2024-10-23 11:09:39.287 [pool-8-thread-1] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because "pkNames" is null
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because "pkNames" is null
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:157)
	at com.alibaba.otter.canal.client.adapter.ProxyOuterAdapter.sync(ProxyOuterAdapter.java:42)
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.batchSync(AdapterProcessor.java:142)
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$writeOut$1(AdapterProcessor.java:100)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$writeOut$2(AdapterProcessor.java:97)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because "pkNames" is null
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbMirrorDbSyncService.initMappingConfig(RdbMirrorDbSyncService.java:140)
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbMirrorDbSyncService.sync(RdbMirrorDbSyncService.java:82)
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:155)
	... 9 common frames omitted

```

**Comment by dyrnq** [comment]
Obviously, the table does not have a PK primary key. The error disappears after adding a primary key to the original table.
