### ISSUE TITLE
Caused by: java.io.IOException: Error When doing Client Authentication:ErrorPacket [errorNumber=1045, fieldCount=-1, message=Access denied for user 'canal'@'172.224.0.155' (using password: YES), sqlState=28000, sqlStateMarker=#]

### ISSUE THREAD

**Issue by dyrnq** [dyrnq/docker-canal#3]
```bash
2024-10-18 08:05:02.563 [canal-instance-scan-0] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2024-10-18 08:05:02.564 [destination = example , address = main-db/172.224.0.4:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address main-db/172.224.0.4:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect main-db/172.224.0.4:3306 failure
Caused by: java.io.IOException: connect main-db/172.224.0.4:3306 failure
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:85)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:104)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:89)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:171)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Error When doing Client Authentication:ErrorPacket [errorNumber=1045, fieldCount=-1, message=Access denied for user 'root'@'172.224.0.155' (using password: YES), sqlState=28000, sqlStateMarker=#]
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.negotiate(MysqlConnector.java:325)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:81)
	... 4 common frames omitted
2024-10-18 08:05:02.564 [destination = example , address = main-db/172.224.0.4:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect main-db/172.224.0.4:3306 failure
Caused by: java.io.IOException: connect main-db/172.224.0.4:3306 failure
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:85)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:104)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:89)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:171)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Error When doing Client Authentication:ErrorPacket [errorNumber=1045, fieldCount=-1, message=Access denied for user 'root'@'172.224.0.155' (using password: YES), sqlState=28000, sqlStateMarker=#]
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.negotiate(MysqlConnector.java:325)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:81)
	... 4 more
]
2024-10-18 08:05:19.341 [destination = example , address = main-db/172.224.0.4:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address main-db/172.224.0.4:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect main-db/172.224.0.4:3306 failure
Caused by: java.io.IOException: connect main-db/172.224.0.4:3306 failure
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:85)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:104)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:89)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:171)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Error When doing Client Authentication:ErrorPacket [errorNumber=1045, fieldCount=-1, message=Access denied for user 'root'@'172.224.0.155' (using password: YES), sqlState=28000, sqlStateMarker=#]
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.negotiate(MysqlConnector.java:325)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:81)
	... 4 common frames omitted

```

**Comment by dyrnq** [comment]
<https://github.com/alibaba/canal/issues/3516>

**Comment by dyrnq** [comment]
- <https://github.com/alibaba/canal/issues/3516>
- <https://github.com/alibaba/canal/issues/5298>

**Comment by dyrnq** [comment]
```bash
SELECT User, Host FROM mysql.user WHERE User = 'canal';
SHOW GRANTS FOR 'canal'@'%';

```

**Comment by dyrnq** [comment]
```bash
SELECT User, Host FROM mysql.user WHERE User = 'canal'
User	Host
canal	%
1 row (0.000 s) Edit, Explain, Export

SHOW GRANTS FOR 'canal'@'%'
Grants for canal@%
GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'canal'@'%'

```

**Comment by dyrnq** [comment]
```bash
environment:
  - MYSQL_ROOT_PASSWORD=666666
```

vs

```bash
environment:
  - MYSQL_ROOT_PASSWORD="666666"
``` 

要想密码是`666666`不需要带双引号，如果带了双引号密码也跟着变为`"666666"`

**Comment by dyrnq** [comment]
- <https://github.com/alibaba/canal/issues/1660>

**Comment by dyrnq** [comment]
Fixed by
```bash
CREATE USER canal IDENTIFIED WITH mysql_native_password BY 'canal';
GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'canal'@'%';
-- GRANT ALL PRIVILEGES ON *.* TO 'canal'@'%' ;
FLUSH PRIVILEGES;
```

**Comment by Levi-Elvin** [comment]
> * [账号拒绝错误 alibaba/canal#3516](https://github.com/alibaba/canal/issues/3516)
> * [1.1.8-alpha-3连接MYSQL8.4总是报错，帮我看看啥原因到底！！！canal.properties和instance.properties还有报错日志、用户权限都已贴上！！！！ alibaba/canal#5298](https://github.com/alibaba/canal/issues/5298)



> ```shell
> SELECT User, Host FROM mysql.user WHERE User = 'canal'
> User	Host
> canal	%
> 1 row (0.000 s) Edit, Explain, Export
> 
> SHOW GRANTS FOR 'canal'@'%'
> Grants for canal@%
> GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'canal'@'%'
> ```

不行 我的还是报错。
[destination = example , address = localhost/127.0.0.1:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect localhost/127.0.0.1:3306 failure
Caused by: java.io.IOException: connect localhost/127.0.0.1:3306 failure
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:85)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:104)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:89)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:171)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.io.IOException: Error When doing Client Authentication:ErrorPacket [errorNumber=1045, fieldCount=-1, message=Access denied for user 'canal'@'localhost' (using password: YES), sqlState=28000, sqlStateMarker=#]
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.negotiate(MysqlConnector.java:325)
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:81)
        ... 4 more
]
@dyrnq

**Comment by Levi-Elvin** [comment]
> Fixed by
> 
> ```shell
> CREATE USER canal IDENTIFIED WITH mysql_native_password BY 'canal';
> GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'canal'@'%';
> -- GRANT ALL PRIVILEGES ON *.* TO 'canal'@'%' ;
> FLUSH PRIVILEGES;
> ```

你可以把你的canal发我嘛，我对比下配置，还有java代码的配置 @dyrnq

**Comment by dyrnq** [comment]
@Levi-Elvin 配置就在这个项目中 
- <https://github.com/dyrnq/docker-canal/tree/main/usage-demo/compose>
