### ISSUE TITLE
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Binary log is not open

### ISSUE THREAD

**Issue by dyrnq** [dyrnq/docker-canal#31]
```bash
19:41:25.970 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - disConnect MysqlConnection to main-db5/172.224.0.2:3306...
19:41:36.722 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection to main-db5/172.224.0.2:3306...
19:41:36.722 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
19:41:36.723 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth plugin: mysql_native_password
19:41:36.723 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - client authentication packet is sent out.
19:41:36.726 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection in sslMode DISABLED, Ssl_version:, Ssl_cipher:
19:41:36.733 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection to main-db5/172.224.0.2:3306...
19:41:36.734 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
19:41:36.734 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth plugin: mysql_native_password
19:41:36.735 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - client authentication packet is sent out.
19:41:36.737 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection in sslMode DISABLED, Ssl_version:, Ssl_cipher:
19:41:36.739 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] WARN  c.a.o.c.p.i.m.r.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
19:41:36.739 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - disConnect MysqlConnection to main-db5/172.224.0.2:3306...
19:41:36.740 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection to main-db5/172.224.0.2:3306...
19:41:36.740 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
19:41:36.740 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth plugin: mysql_native_password
19:41:36.741 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - client authentication packet is sent out.
19:41:36.743 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection in sslMode DISABLED, Ssl_version:, Ssl_cipher:
19:41:36.753 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] WARN  c.a.o.c.p.i.mysql.MysqlConnection - load MySQL @@version_comment : MySQL Community Server (GPL)
19:41:36.753 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.i.mysql.MysqlConnection - COM_BINLOG_DUMP with position:BinlogDumpCommandPacket[binlogPosition=4,slaveServerId=5555555,binlogFileName=mysql-bin.000001,command=18]
19:41:36.754 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] ERROR c.a.o.c.p.i.m.d.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Binary log is not open
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:167)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:787)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findPositionWithMasterIdAndTimestamp(MysqlEventParser.java:401)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:447)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:360)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:186)
        at java.base/java.lang.Thread.run(Thread.java:1583)
19:41:36.754 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] ERROR c.a.o.c.p.i.m.r.RdsBinlogEventParserProxy - ERROR ## findAsPerTimestampInSpecificLogFile has an error
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Binary log is not open
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:167)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:787)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findPositionWithMasterIdAndTimestamp(MysqlEventParser.java:401)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:447)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:360)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:186)
        at java.base/java.lang.Thread.run(Thread.java:1583)
19:41:36.754 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] ERROR c.a.o.c.p.i.m.r.RdsBinlogEventParserProxy - dump address main-db5/172.224.0.2:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: [fixed timestamp] can't found begin/commit position before with fixed position mysql-bin.000001:4
19:41:36.754 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] ERROR c.a.o.c.common.alarm.LogAlarmHandler - destination:test[com.alibaba.otter.canal.parse.exception.CanalParseException: [fixed timestamp] can't found begin/commit position before with fixed position mysql-bin.000001:4
]
19:41:36.754 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - disConnect MysqlConnection to main-db5/172.224.0.2:3306...
19:41:36.755 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - disConnect MysqlConnection to main-db5/172.224.0.2:3306...
19:41:36.755 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection to main-db5/172.224.0.2:3306...
19:41:36.755 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
19:41:36.755 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - auth plugin: mysql_native_password
19:41:36.756 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - client authentication packet is sent out.
19:41:36.758 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - connect MysqlConnection in sslMode DISABLED, Ssl_version:, Ssl_cipher:
19:41:36.763 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - KILL DUMP 35 failure
java.io.IOException: ErrorPacket [errorNumber=1094, fieldCount=-1, message=Unknown thread id: 35, sqlState=HY000, sqlStateMarker=#]
 with command: KILL CONNECTION 35
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlUpdateExecutor.update(MysqlUpdateExecutor.java:49)
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:137)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.disconnect(MysqlConnection.java:112)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:307)
        at java.base/java.lang.Thread.run(Thread.java:1583)
19:41:36.763 [destination = test , address = main-db5/172.224.0.2:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - disConnect MysqlConnection to main-db5/172.224.0.2:3306...

```

**Comment by dyrnq** [comment]
`Binary log is not open`此错误为mysql的binlog没有开启，设置为开启后错误消息。
