### ISSUE TITLE
ERROR c.a.o.c.admin.handler.SessionHandler - something goes wrong with channel:[id: 0x5551c293, /10.0.2.15:42518 => /10.244.19.255:11110], exception=java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by dyrnq** [dyrnq/docker-canal#34]
```bash
14:30:38.982 [New I/O server worker #1-5] ERROR c.a.o.c.admin.handler.SessionHandler - something goes wrong with channel:[id: 0x21d165ec, /10.0.2.15:46980 => /10.244.19.255:11110], exception=java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:401)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:434)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:323)
	at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:282)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:202)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

14:30:48.983 [New I/O server boss #1 ([id: 0x0530712d, /0.0.0.0:11110])] INFO  c.a.o.c.a.h.HandshakeInitializationHandler - send handshake initialization packet to : [id: 0x3872cf95, /10.0.2.15:3604 => /10.244.19.255:11110]
14:30:48.984 [New I/O server worker #1-6] INFO  c.a.o.c.a.h.HandshakeInitializationHandler - remove unused channel handlers after authentication is done successfully.
14:30:58.983 [New I/O server boss #1 ([id: 0x0530712d, /0.0.0.0:11110])] INFO  c.a.o.c.a.h.HandshakeInitializationHandler - send handshake initialization packet to : [id: 0x5551c293, /10.0.2.15:42518 => /10.244.19.255:11110]
14:30:58.983 [New I/O server worker #1-7] INFO  c.a.o.c.a.h.HandshakeInitializationHandler - remove unused channel handlers after authentication is done successfully.
14:30:58.984 [New I/O server worker #1-7] ERROR c.a.o.c.admin.handler.SessionHandler - something goes wrong with channel:[id: 0x5551c293, /10.0.2.15:42518 => /10.244.19.255:11110], exception=java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:401)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:434)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:323)
	at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:282)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:202)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

14:31:08.982 [New I/O server boss #1 ([id: 0x0530712d, /0.0.0.0:11110])] INFO  c.a.o.c.a.h.HandshakeInitializationHandler - send handshake initialization packet to : [id: 0x77f2965a, /10.0.2.15:10846 => /10.244.19.255:11110]
14:31:08.982 [New I/O server worker #1-8] INFO  c.a.o.c.a.h.HandshakeInitializationHandler - remove unused channel handlers after authentication is done successfully.
14:31:08.982 [New I/O server worker #1-8] ERROR c.a.o.c.admin.handler.SessionHandler - something goes wrong with channel:[id: 0x77f2965a, /10.0.2.15:10846 => /10.244.19.255:11110], exception=java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:401)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:434)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:323)
	at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:282)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:202)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

14:31:18.982 [New I/O server boss #1 ([id: 0x0530712d, /0.0.0.0:11110])] INFO  c.a.o.c.a.h.HandshakeInitializationHandler - send handshake initialization packet to : [id: 0x5d26634d, /10.0.2.15:1438 => /10.244.19.255:11110]
14:31:18.983 [New I/O server worker #1-1] INFO  c.a.o.c.a.h.HandshakeInitializationHandler - remove unused channel handlers after authentication is done successfully.
14:31:28.987 [New I/O server boss #1 ([id: 0x0530712d, /0.0.0.0:11110])] INFO  c.a.o.c.a.h.HandshakeInitializationHandler - send handshake initialization packet to : [id: 0x7306011b, /10.0.2.15:63204 => /10.244.19.255:11110]
14:31:28.991 [New I/O server worker #1-2] INFO  c.a.o.c.a.h.HandshakeInitializationHandler - remove unused channel handlers after authentication is done successfully.

```

**Comment by dyrnq** [comment]
Fixed by <https://github.com/dyrnq/docker-canal/commit/8aebd5c767e6d555c54f052a2bc6481ad07270f2>.

Amend canal-server livenessProbe use 11112, replace 11110.
