### ISSUE TITLE
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by dyrnq** [dyrnq/docker-canal#6]
```bash
2024-10-19 04:33:59.489 [canal-instance-scan-0] ERROR c.a.o.canal.instance.manager.PlainCanalInstanceGenerator - generator instance failed.
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'instance' defined in class path resource [spring/default-instance.xml]: Cannot resolve reference to bean 'eventParser' while setting bean property 'eventParser'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'eventParser' defined in class path resource [spring/default-instance.xml]: Cannot create inner bean 'com.alibaba.otter.canal.parse.index.FailbackLogPositionManager#283a9f32' of type [com.alibaba.otter.canal.parse.index.FailbackLogPositionManager] while setting bean property 'logPositionManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.otter.canal.parse.index.FailbackLogPositionManager#283a9f32' defined in class path resource [spring/default-instance.xml]: Cannot create inner bean 'com.alibaba.otter.canal.parse.index.MetaLogPositionManager#2e50443c' of type [com.alibaba.otter.canal.parse.index.MetaLogPositionManager] while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.otter.canal.parse.index.MetaLogPositionManager#2e50443c' defined in class path resource [spring/default-instance.xml]: Cannot resolve reference to bean 'metaManager' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metaManager' defined in class path resource [spring/default-instance.xml]: Cannot create inner bean 'com.alibaba.otter.canal.meta.ZooKeeperMetaManager#5518c7a3' of type [com.alibaba.otter.canal.meta.ZooKeeperMetaManager] while setting bean property 'zooKeeperMetaManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.otter.canal.meta.ZooKeeperMetaManager#5518c7a3' defined in class path resource [spring/default-instance.xml]: Cannot resolve reference to bean 'zkClientx' while setting bean property 'zkClientx'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'zkClientx' defined in class path resource [spring/default-instance.xml]: Invocation of init method failed; nested exception is com.google.common.util.concurrent.UncheckedExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1707)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1452)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:85)
	at com.alibaba.otter.canal.instance.manager.PlainCanalInstanceGenerator.getBeanFactory(PlainCanalInstanceGenerator.java:76)
	at com.alibaba.otter.canal.instance.manager.PlainCanalInstanceGenerator.generate(PlainCanalInstanceGenerator.java:53)
	at com.alibaba.otter.canal.deployer.CanalController.lambda$initGlobalConfig$2(CanalController.java:388)
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.lambda$start$0(CanalServerWithEmbedded.java:81)
	at com.google.common.collect.MigrateMap$1.load(MigrateMap.java:23)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)
	at com.google.common.collect.MigrateMap$MigrateConcurrentMap.get(MigrateMap.java:68)
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.start(CanalServerWithEmbedded.java:130)
	at com.alibaba.otter.canal.deployer.CanalController$1.processActiveEnter(CanalController.java:166)
	at com.alibaba.otter.canal.common.zookeeper.running.ServerRunningMonitor.processActiveEnter(ServerRunningMonitor.java:247)
	at com.alibaba.otter.canal.common.zookeeper.running.ServerRunningMonitor.start(ServerRunningMonitor.java:100)
	at com.alibaba.otter.canal.deployer.CanalController$2.start(CanalController.java:253)
	at com.alibaba.otter.canal.deployer.monitor.ManagerInstanceConfigMonitor.notifyStart(ManagerInstanceConfigMonitor.java:124)
	at com.alibaba.otter.canal.deployer.monitor.ManagerInstanceConfigMonitor.lambda$scan$5(ManagerInstanceConfigMonitor.java:117)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.alibaba.otter.canal.deployer.monitor.ManagerInstanceConfigMonitor.scan(ManagerInstanceConfigMonitor.java:116)
	at com.alibaba.otter.canal.deployer.monitor.ManagerInstanceConfigMonitor.lambda$start$1(ManagerInstanceConfigMonitor.java:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'eventParser' defined in class path resource [spring/default-instance.xml]: Cannot create inner bean 'com.alibaba.otter.canal.parse.index.FailbackLogPositionManager#283a9f32' of type [com.alibaba.otter.canal.parse.index.FailbackLogPositionManager] while setting bean property 'logPositionManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.otter.canal.parse.index.FailbackLogPositionManager#283a9f32' defined in class path resource [spring/default-instance.xml]: Cannot create inner bean 'com.alibaba.otter.canal.parse.index.MetaLogPositionManager#2e50443c' of type [com.alibaba.otter.canal.parse.index.MetaLogPositionManager] while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.otter.canal.parse.index.MetaLogPositionManager#2e50443c' defined in class path resource [spring/default-instance.xml]: Cannot resolve reference to bean 'metaManager' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metaManager' defined in class path resource [spring/default-instance.xml]: Cannot create inner bean 'com.alibaba.otter.canal.meta.ZooKeeperMetaManager#5518c7a3' of type [com.alibaba.otter.canal.meta.ZooKeeperMetaManager] while setting bean property 'zooKeeperMetaManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.otter.canal.meta.ZooKeeperMetaManager#5518c7a3' defined in class path resource [spring/default-instance.xml]: Cannot resolve reference to bean 'zkClientx' while setting bean property 'zkClientx'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'zkClientx' defined in class path resource [spring/default-instance.xml]: Invocation of init method failed; nested exception is com.google.common.util.concurrent.UncheckedExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:389)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:127)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1707)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1452)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330)
	... 43 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.otter.canal.parse.index.FailbackLogPositionManager#283a9f32' defined in class path resource [spring/default-instance.xml]: Cannot create inner bean 'com.alibaba.otter.canal.parse.index.MetaLogPositionManager#2e50443c' of type [com.alibaba.otter.canal.parse.index.MetaLogPositionManager] while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.otter.canal.parse.index.MetaLogPositionManager#2e50443c' defined in class path resource [spring/default-instance.xml]: Cannot resolve reference to bean 'metaManager' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metaManager' defined in class path resource [spring/default-instance.xml]: Cannot create inner bean 'com.alibaba.otter.canal.meta.ZooKeeperMetaManager#5518c7a3' of type [com.alibaba.otter.canal.meta.ZooKeeperMetaManager] while setting bean property 'zooKeeperMetaManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.otter.canal.meta.ZooKeeperMetaManager#5518c7a3' defined in class path resource [spring/default-instance.xml]: Cannot resolve reference to bean 'zkClientx' while setting bean property 'zkClientx'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'zkClientx' defined in class path resource [spring/default-instance.xml]: Invocation of init method failed; nested exception is com.google.common.util.concurrent.UncheckedExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:389)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:127)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:707)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:198)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:374)
	... 53 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.otter.canal.parse.index.MetaLogPositionManager#2e50443c' defined in class path resource [spring/default-instance.xml]: Cannot resolve reference to bean 'metaManager' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metaManager' defined in class path resource [spring/default-instance.xml]: Cannot create inner bean 'com.alibaba.otter.canal.meta.ZooKeeperMetaManager#5518c7a3' of type [com.alibaba.otter.canal.meta.ZooKeeperMetaManager] while setting bean property 'zooKeeperMetaManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.otter.canal.meta.ZooKeeperMetaManager#5518c7a3' defined in class path resource [spring/default-instance.xml]: Cannot resolve reference to bean 'zkClientx' while setting bean property 'zkClientx'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'zkClientx' defined in class path resource [spring/default-instance.xml]: Invocation of init method failed; nested exception is com.google.common.util.concurrent.UncheckedExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:707)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:198)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:374)
	... 61 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metaManager' defined in class path resource [spring/default-instance.xml]: Cannot create inner bean 'com.alibaba.otter.canal.meta.ZooKeeperMetaManager#5518c7a3' of type [com.alibaba.otter.canal.meta.ZooKeeperMetaManager] while setting bean property 'zooKeeperMetaManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.otter.canal.meta.ZooKeeperMetaManager#5518c7a3' defined in class path resource [spring/default-instance.xml]: Cannot resolve reference to bean 'zkClientx' while setting bean property 'zkClientx'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'zkClientx' defined in class path resource [spring/default-instance.xml]: Invocation of init method failed; nested exception is com.google.common.util.concurrent.UncheckedExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:389)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:127)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1707)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1452)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330)
	... 69 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.otter.canal.meta.ZooKeeperMetaManager#5518c7a3' defined in class path resource [spring/default-instance.xml]: Cannot resolve reference to bean 'zkClientx' while setting bean property 'zkClientx'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'zkClientx' defined in class path resource [spring/default-instance.xml]: Invocation of init method failed; nested exception is com.google.common.util.concurrent.UncheckedExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1707)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1452)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:374)
	... 79 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'zkClientx' defined in class path resource [spring/default-instance.xml]: Invocation of init method failed; nested exception is com.google.common.util.concurrent.UncheckedExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330)
	... 85 common frames omitted
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2218)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)
	at com.google.common.collect.MigrateMap$MigrateConcurrentMap.get(MigrateMap.java:68)
	at com.alibaba.otter.canal.common.zookeeper.ZkClientx.getZkClient(ZkClientx.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:283)
	at org.springframework.beans.factory.config.MethodInvokingBean.invokeWithTargetException(MethodInvokingBean.java:123)
	at org.springframework.beans.factory.config.MethodInvokingFactoryBean.afterPropertiesSet(MethodInvokingFactoryBean.java:108)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	... 92 common frames omitted
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/java.util.Arrays$ArrayList.get(Arrays.java:4351)
	at com.alibaba.otter.canal.common.zookeeper.ZooKeeperx.connect(ZooKeeperx.java:68)
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1228)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:157)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:131)
	at com.alibaba.otter.canal.common.zookeeper.ZkClientx.<init>(ZkClientx.java:56)
	at com.alibaba.otter.canal.common.zookeeper.ZkClientx.<init>(ZkClientx.java:52)
	at com.alibaba.otter.canal.common.zookeeper.ZkClientx.<init>(ZkClientx.java:40)
	at com.alibaba.otter.canal.common.zookeeper.ZkClientx.<init>(ZkClientx.java:36)
	at com.google.common.collect.MigrateMap$1.load(MigrateMap.java:23)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
	... 106 common frames omitted

```

**Comment by dyrnq** [comment]
没有配置`canal.zkServers`
