### ISSUE TITLE
"java.nio.file.FileSystemException: /home/admin/canal-server/conf/example/h2.trace.db: Read-only file system" [90034-210]

### ISSUE THREAD

**Issue by dyrnq** [dyrnq/docker-canal#9]
```bash
org.h2.message.DbException: Log file error: "/home/admin/canal-server/conf/example/h2.trace.db", cause: "java.nio.file.FileSystemException: /home/admin/canal-server/conf/example/h2.trace.db: Read-only file system" [90034-210]
org.h2.message.DbException: Log file error: "/home/admin/canal-server/conf/example/h2.trace.db", cause: "java.nio.file.FileSystemException: /home/admin/canal-server/conf/example/h2.trace.db: Read-only file system" [90034-210]
	at org.h2.message.DbException.get(DbException.java:216)
	at org.h2.message.TraceSystem.logWritingError(TraceSystem.java:294)
	at org.h2.message.TraceSystem.openWriter(TraceSystem.java:315)
	at org.h2.message.TraceSystem.writeFile(TraceSystem.java:263)
	at org.h2.message.TraceSystem.write(TraceSystem.java:247)
	at org.h2.message.Trace.error(Trace.java:173)
	at org.h2.engine.Database.setBackgroundException(Database.java:1808)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:120)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3296)
	at org.h2.mvstore.MVStore.panic(MVStore.java:585)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:461)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4056)
	at org.h2.mvstore.db.Store.<init>(Store.java:129)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1694)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1794)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2967)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Log file error: "/home/admin/canal-server/conf/example/h2.trace.db", cause: "java.nio.file.FileSystemException: /home/admin/canal-server/conf/example/h2.trace.db: Read-only file system" [90034-210]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	... 23 more
Caused by: java.nio.file.FileSystemException: /home/admin/canal-server/conf/example/h2.trace.db: Read-only file system
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:482)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:227)
	at org.h2.store.fs.disk.FilePathDisk.newOutputStream(FilePathDisk.java:363)
	at org.h2.store.fs.FileUtils.newOutputStream(FileUtils.java:296)
	at org.h2.message.TraceSystem.openWriter(TraceSystem.java:312)
	... 20 more

```

**Comment by dyrnq** [comment]
```bash
# table meta tsdb info
canal.instance.tsdb.enable=true
#canal.instance.tsdb.url=jdbc:mysql://127.0.0.1:3306/canal_tsdb
#canal.instance.tsdb.dbUsername=canal
#canal.instance.tsdb.dbPassword=canal
```

```bash
# table meta tsdb info
canal.instance.tsdb.enable = true
canal.instance.tsdb.dir = ${canal.file.data.dir:../conf}/${canal.instance.destination:}
canal.instance.tsdb.url = jdbc:h2:${canal.instance.tsdb.dir}/h2;CACHE_SIZE=1000;MODE=MYSQL;
canal.instance.tsdb.dbUsername = canal
canal.instance.tsdb.dbPassword = canal
# dump snapshot interval, default 24 hour
canal.instance.tsdb.snapshot.interval = 24
# purge snapshot expire , default 360 hour(15 days)
canal.instance.tsdb.snapshot.expire = 360
```


[spring/tsdb/h2-tsdb.xml](https://github.com/alibaba/canal/blob/master/deployer/src/main/resources/spring/tsdb/h2-tsdb.xml)

**Comment by dyrnq** [comment]
`canal.instance.tsdb.enable` 是 Canal 配置中的一个关键选项，用于启用或禁用时间序列数据库（TSDB）功能。其主要作用如下：
### 主要作用
- 存储表结构元数据：
启用 TSDB 功能后，Canal 会使用数据库（如 H2 或 MySQL）来缓存解析的表结构。这可以帮助 Canal 在处理 binlog 时，快速访问和比较表的元数据，以应对表结构的变化。
- 应对表结构变更：
当上游数据库的表结构发生变化时，TSDB 可以帮助 Canal 识别这些变化，从而避免因结构不匹配而导致的解析异常。例如，如果表的字段数量发生变化，TSDB 可以提供最新的元数据以供比较，从而减少解析错误的发生[1](https://www.cnblogs.com/throwable/p/13449920.html)[3](https://blog.csdn.net/qq_27275851/article/details/117283445)[4](https://www.dboop.com/ops/canal%E5%B8%B8%E7%94%A8%E9%85%8D%E7%BD%AE%E9%A1%B9%E6%95%B4%E7%90%86%E5%92%8C%E6%8A%A5%E9%94%99%E5%A4%84%E7%90%86/)。
- 提高容错能力：
在高可用（HA）环境中，如果一个 Canal 实例宕机并切换到另一个实例，TSDB 可以确保新的实例能够正确解析之前未处理的 binlog，减少数据丢失的风险[2](https://cloud.tencent.com/developer/article/1755921)[5](https://www.liwenzhou.com/posts/Go/canal/)。
### 注意事项
- 性能影响：虽然启用 TSDB 可以提高容错能力和处理灵活性，但在某些情况下，如频繁的表结构变更，可能会导致性能问题。因此，有时建议在生产环境中禁用此功能，以避免潜在的解析阻塞[1](https://www.cnblogs.com/throwable/p/13449920.html)[2](https://cloud.tencent.com/developer/article/1755921)。
- 默认设置：在 Canal 的默认配置中，TSDB 功能通常是启用的，但用户可以根据具体需求进行调整。

综上所述，canal.instance.tsdb.enable 的设置对于确保 Canal 在处理数据库变更时的稳定性和可靠性至关重要。
